# Generated by Django 4.1.3 on 2022-11-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_uuid_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uuid',
        ),
    ]
